# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Hugo Product Launch"
license = "Creative Commons Attribution 4.0 International Public License (CC BY 4.0)"
licenselink = "https://github.com/janraasch/hugo-product-launch/blob/master/LICENSE"
description = "A Hugo theme for young start-ups, product launches, and »coming soon«-websites. Includes contact form & newsletter sign up via Netlify. Deploy with one click!"
homepage = "https://github.com/janraasch/hugo-product-launch"
demosite = "https://hugo-product-launch.netlify.app"
tags = [
  "bootstrap",
  "company",
  "contact",
  "landing",
  "minimal",
  "netlify",
  "starter",
  "tailwind",
]
features = [
  "cover-image",
  "favicon",
  "responsive",
  "fast",
  "tailwind",
  "contact",
  "newsletter sign-up",
  "netlify",
  "netlify forms"
]
min_version = "v0.147.4"

[author]
  name = "Jan Raasch"
  homepage = "https://www.janraasch.com"
