---
label: Configuration
hide_body: true
fields:
  - type: text
    name: baseURL
    label: baseURL
    description:
      Hostname (and path) to the root, e.g. <a href="https://bep.is/" title="https://bep.is/"
      target="_blank">https://bep.is/</a> - See <a href="https://gohugo.io/getting-started/configuration/"
      title="https://gohugo.io/getting-started/configuration/" target="_blank">https://gohugo.io/getting-started/configuration/</a>
  - type: list
    name: disableKinds
    label: disableKinds
    description:
      This is a "one page"-website, so we do not need these kinds of pages...
      See <a href="https://gohugo.io/getting-started/configuration/" title="https://gohugo.io/getting-started/configuration/"
      target="_blank">https://gohugo.io/getting-started/configuration/</a>
  - type: text
    name: defaultContentLanguage
    label: defaultContentLanguage
    description:
      Content without language indicator will default to this language. See
      <a href="https://gohugo.io/getting-started/configuration/" title="https://gohugo.io/getting-started/configuration/"
      target="_blank">https://gohugo.io/getting-started/configuration/</a>
  - type: text
    name: theme
    label: theme
    description: The name of this wonderful theme ;-).
  - type: text
    name: title
    label: title
    description: The "title" of your website.
  - type: field_group
    name: markup
    label: markup
    fields:
      - type: field_group
        name: goldmark
        label: goldmark
        fields:
          - type: field_group
            name: renderer
            label: renderer
            fields:
              - type: boolean
                name: hardWraps
                label: hardWraps
    description:
      Render line-breaks in .md-files as line-breaks in HTML.<br><br>This
      is e.g. useful for rendering a multi-line address.<br><br>See <a href="https://gohugo.io/getting-started/configuration-markup#configure-markup"
      title="https://gohugo.io/getting-started/configuration-markup#configure-markup"
      target="_blank">https://gohugo.io/getting-started/configuration-markup#configure-markup</a>.
  - type: field_group
    name: params
    label: params
    fields:
      - type: text
        name: copyright
        label: copyright
        description:
          'A "copyright"-line to be added at the bottom of the page.<br><br>Hint:
          Markdown is supported in here as well. So you may e.g. add a link to your legal
          imprint-page.'
      - type: text
        name: description
        label: description
        description:
          The "description" of your website. This is used in the meta data
          of your generated html.
      - type: file
        name: favicon
        label: favicon
        description:
          'The path to your "favicon". This should be a square (at least 32px
          x 32px) png-file.<br><br>Hint: It''s good practise to also put a "favicon.ico"-file
          into your "static"-folder.'
      - type: image_gallery
        name: images
        label: images
        description:
          These "images" are used for the structured data templates. This will
          show up, when services like Twitter or Slack want to generate a preview of a
          link to your site. See <a href="https://gohugo.io/templates/internal#twitter-cards"
          title="https://gohugo.io/templates/internal#twitter-cards" target="_blank">https://gohugo.io/templates/internal#twitter-cards</a>
          and <a href="https://gohugo.io/templates/internal#open-graphhttps://gohugo.io/templates/internal#open-graph"
          title="https://gohugo.io/templates/internal#open-graph" target="_blank">https://gohugo.io/templates/internal#open-graph</a>.
      - type: text
        name: title
        label: title
        description:
          Another "title" :-). This one is used as the site_name on Hugo's
          internal opengraph structured data template. See <a href="https://ogp.me/" title="https://ogp.me/"
          target="_blank">https://ogp.me/</a> and <a href="https://gohugo.io/templates/internal#open-graph"
          title="https://gohugo.io/templates/internal#open-graph" target="_blank">https://gohugo.io/templates/internal#open-graph</a>.
      - type: field_group
        name: meta
        label: meta
        fields:
          - type: text
            name: keywords
            label: keywords
      - name: hidedesignbyline
        type: boolean
        label: hidedesignbyline
        description:
          '<strong>LICENSE</strong>: Hugo Product Launch by Jan Raasch is licensed
          under Attribution 4.0 International (CC BY 4.0). See <a href="https://github.com/janraasch/hugo-product-launch#license."
          title="https://github.com/janraasch/hugo-product-launch#license." target="_blank">https://github.com/janraasch/hugo-product-launch#license.</a>
          <br><br>This theme will, by default, inject a design-by-line at the bottom of
          the page.<br><br> <strong>If</strong> you would like to use this theme <strong>without
          attribution</strong>, permissions beyond this license''s scope <strong>are available</strong>
          at <a href="https://github.com/janraasch/hugo-product-launch/blob/master/MORE_PERMISSIONS.md."
          title="https://github.com/janraasch/hugo-product-launch/blob/master/MORE_PERMISSIONS.md"
          target="_blank">https://github.com/janraasch/hugo-product-launch/blob/master/MORE_PERMISSIONS.md</a>.'
        default: false
pages:
  - config.toml
